### ISSUE TITLE
Batching

### ISSUE THREAD

**Issue by ganondev** [nayaverdier/dyntastic#1]
Is there any plan to wrap the batch read or write methods available in boto3?

Perhaps something like:
```
Event.batch_get(
    "key1",
    "key2",
    "key3"
)
```

**Comment by nayaverdier** [comment]
@ganondev I'd definitely like to support dynamo batching in this library. Feel free to submit a PR, otherwise I can take a stab in the next couple of weeks.

**Comment by nayaverdier** [comment]
@ganondev Finally got around to this, `dyntastic==0.6.0` now supports batched reads and writes: [README](https://github.com/nayaverdier/dyntastic#batch-reads).
