### ISSUE TITLE
Localstack support

### ISSUE THREAD

**Issue by wesleyearlstander** [nayaverdier/dyntastic#18]
Hi team,

I'm currently very interested in using this for my projects.

One thing that I'd like to get out of the box is Localstack support for the models so that the host automatically gets rewritten to the Localstack when Localstack is configured.

I'm adding this issue here as I think it would be a nice QOL upgrade, and perhaps I will get to it if I find time.

**Comment by nayaverdier** [comment]
What mechanism would you propose to detect whether localstack is configured? Currently if the `DYNTASTIC_HOST` environment variable is defined, it will pull the host value from that by default.

**Comment by wesleyearlstander** [comment]
Okay that works for me.

From the examples I thought I needed to set it on each model.

**Comment by AidanStrong** [comment]
Reopening this issue as I have a related problem. 

I am using localstack for dynamodb but my python ode is running in a seprate docker container, so I need to use AWS ACCESS_ID and ACCESS_KEY to authenticate to my local dynamodb - I see no option to do this with dyntastic. Am I mistaken or is this feature yet to be added?
