### ISSUE TITLE
Consider removing the dependency pinning

### ISSUE THREAD

**Issue by jsjeannotte** [nayaverdier/dyntastic#2]
Hi! We just started trying to integrate your library to our ecosystem but this is causing some conflicts with other libraries (because of the pinning of `importlib-metadata` at the moment, but the other two pinnings will eventually cause trouble as well). Would you consider removing the pinning?

Thank you!

**Comment by nayaverdier** [comment]
@jsjeannotte Would it be sufficient to change the requirements to the following?
```python
install_requires=[
    "boto3>=1.10.0",
    "pydantic>=1.7.1",
    "importlib-metadata>=1.0.0; python_version <= '3.8'",
]
```

**Comment by nayaverdier** [comment]
@jsjeannotte Give `0.7.0a1` a go. If that works well for you, I will release it as `0.7.0`.

**Comment by jsjeannotte** [comment]
Gave it a go. All good now, no more conflicts. Thanks!

**Comment by nayaverdier** [comment]
@jsjeannotte Just deployed `0.7.0`!
