### ISSUE TITLE
Empty ExpressionAttributeValues causes validation error in transaction put item 

### ISSUE THREAD

**Issue by regoawt** [nayaverdier/dyntastic#27]
Hi, 

Firstly thanks for this library, it's great.

I'm trying to run a transaction that includes a PutItem action with a conditional check, however it fails with `An error occurred (ValidationException) when calling the TransactWriteItems operation: ExpressionAttributeValues must not be empty`.

I did some digging and it looks like the `_construct_transact_item` method builds the transaction item with an empty `ExpressionAttributeValues`. For reference, here is the actual code (sensitive info removed) followed by `TransactionWriter.items`:

```
with transaction():
    _globals.update(
        A.tenant_count.set(new_tenant_count), refresh=False
    )
    _globals.ignore_unrefreshed()
    tenant_id = zero_pad(new_tenant_count)
    tenant_pk = f"tenant#{tenant_id}-tenant#{tenant_id}"
    _tenant = Tenant(
        pk=tenant_pk,
        sk=f"tenant#{tenant_id}",
    )
    _tenant.save(condition=A.not_exists(A.pk))
```

```
[{'Update': {'Key': {'pk': {'S': 'globals'}, 'sk': {'S': 'globals'}}, 'UpdateExpression': 'SET #0 = :0', 'ExpressionAttributeNames': {'#0': 'tenant_count'}, 'ExpressionAttributeValues': {':0': {'N': '1'}}, 'TableName': 'EmailAutomation'}}, {'Put': {'Item': {'pk': {'S': 'tenant#0000001-tenant#0000001'}, 'sk': {'S': 'tenant#0000001'}}, 'ConditionExpression': 'attribute_not_exists(#n0)', 'TableName': 'EmailAutomation', 'ExpressionAttributeNames': {'#n0': 'pk'}, 'ExpressionAttributeValues': {}}}]
```

I think it should just be a case of dropping the `ExpressionAttributeValues` entry if it is empty, but haven't tested it.

**Comment by nayaverdier** [comment]
Thanks for the detailed information! It might be worth creating a ticket with moto if you haven't already so its behavior is consistent with actual service.

I'll try to reproduce this sometime this week and see if I can get a fix out.

**Comment by regoawt** [comment]
Yep have done so! https://github.com/getmoto/moto/issues/8405 

I forked Dyntastic and seemed to have resolved the issue by just adding the following to `_construct_transact_item`:
```
if (
            "ExpressionAttributeValues" in filtered_kwargs
            and len(filtered_kwargs.get("ExpressionAttributeValues", {}).keys()) == 0
        ):
            del filtered_kwargs["ExpressionAttributeValues"]
```
https://github.com/Weird-Sheep-Labs/dyntastic

The tests will need quite a bit of reworking due to the underlying moto bug I imagine.

**Comment by nayaverdier** [comment]
@regoawt Included a fix in`0.16.0`, please confirm it's working. Feel free to reopen if it's not. For now I'm hoping moto will be able to update the mocks on their side to avoid the need to dig deep into the inner workings of moto to test this is fixed long term.

**Comment by regoawt** [comment]
Thanks! Sure will get back to you tomorrow.

**Comment by regoawt** [comment]
@nayaverdier looks like it's working fine, thanks a lot!
