### ISSUE TITLE
Feature request: __table_host__ or endpoint_url

### ISSUE THREAD

**Issue by bvsn** [nayaverdier/dyntastic#4]
Hi there 👋 Is there any way to set a custom `endpoint_url` for dynamodb? For local development, I'm using dynamodb docker image, so looking for a way how to set my `http://localhost:8000` for boto3 resource/client 🤔

Any suggestions on how to set it up? Thanks in advance.

**Comment by nayaverdier** [comment]
@bvsn Hey, just released 0.9.0 with the option of setting `__table_host__` as a class variable. Let me know if that works for you.

**Comment by bvsn** [comment]
Cool, will check and back to you soon 🙌

**Comment by bvsn** [comment]
It works perfectly, thank you.
